version: '3.8'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=indigov
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - ./db-seed:/docker-entrypoint-initdb.d
volumes:
  db:
    driver: local
